### ISSUE TITLE
Actions en general

### ISSUE THREAD

**Issue by cesartecnicas** [lucasp90/template-tp-grupal#12]
Tienen el código de las actions en los config.

El pick action está codeado en el config! debería ser un servicio del engine (no el pick, sino la abstracción que está por detrás del pick).

En los config tiene que haber configuración, no lógica. La lógica tiene que ser provista por el engine y el config solo tiene que configurarla.

**Comment by nicotruk** [comment]
![actionhierarchy](https://cloud.githubusercontent.com/assets/17879377/16082701/c2f75628-32e8-11e6-90c5-729ebf61f81a.png)
