### ISSUE TITLE
Permitir comandos en cualquier orden

### ISSUE THREAD

**Issue by AyudantesTecnicas** [lucasp90/template-tp-grupal#3]
Durante la demo, en el juego Abrir puerta, no pudimos abrir la puerta sin realizar primero 'look around'.
El motor debe soportar que se pidan realizar acciones sin imponer un orden, en caso de poder hacerse, realizarla; caso contrario indicar que no es posible realizar la acción.

**Comment by nicotruk** [comment]
Soportado en nueva configuracion
