### ISSUE TITLE
Dar respuesta ante acciones no soportadas

### ISSUE THREAD

**Issue by AyudantesTecnicas** [lucasp90/template-tp-grupal#6]
Si el juego se encuentra en un determinado estado que no permite realizar una acción, indicarlo con un mensaje.

**Comment by lucasp90** [comment]
@AyudantesTecnicas un ejemplo de este issue sería lo ocurrido en la demo de Hanoi? (No se podía mover a una pila, pero el juego respondía que el mensaje no estaba soportado)

**Comment by Flotristant** [comment]
Si
