### ISSUE TITLE
Action What can I do with

### ISSUE THREAD

**Issue by cesartecnicas** [lucasp90/template-tp-grupal#9]
El action what can I do with tiene el nombre del comando hardcoded.
¿Que pasa si un juego quiere invocarlo con un comando distinto?

No es lo mismo un action, que el comando que se usa para invocarla.

Que pasa si para un juego no quiero soportar ese action?
Que pasa si tengo la configuración de un juego en un file?

**Comment by nicotruk** [comment]
Creada la action concreta con la logica correspondiente. Al crear una instancia, se le pasa por parametro el comando con el cual se desea poder invocar la action.
